// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function FaveTile(Props) {
  var post = Props.post;
  var match = React.useState(function () {
        return /* Image */1;
      });
  var setTileState = match[1];
  var possNullImg = post.frontmatter.featuredimage;
  var renderImageJsx = function (param) {
    return React.createElement("div", undefined, (possNullImg == null) ? "placeholderimageMAIN" : React.createElement("div", undefined));
  };
  var renderWordsJsx = function (param) {
    return React.createElement("div", undefined, (possNullImg == null) ? "placeholderimageWORDS" : React.createElement("div", undefined), React.createElement("div", {
                    className: "font-bold text-xl mb-2"
                  }, post.frontmatter.title), React.createElement("p", {
                    className: "text-gray-700 text-base"
                  }, post.excerpt));
  };
  return React.createElement("div", {
              className: "max-w-sm rounded overflow-hidden shadow-lg h-64",
              onMouseEnter: (function (param) {
                  return Curry._1(setTileState, (function (param) {
                                return /* Words */0;
                              }));
                }),
              onMouseLeave: (function (param) {
                  return Curry._1(setTileState, (function (param) {
                                return /* Image */1;
                              }));
                })
            }, React.createElement("div", {
                  className: "px-6 py-4"
                }, match[0] ? renderImageJsx(undefined) : renderWordsJsx(undefined)), React.createElement("div", {
                  className: "px-6 py-4"
                }, React.createElement("span", {
                      className: "inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2"
                    }, "#photography"), React.createElement("span", {
                      className: "inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2"
                    }, "#travel"), React.createElement("span", {
                      className: "inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700"
                    }, "#winter")));
}

var Link;

var make = FaveTile;

var $$default = FaveTile;

exports.Link = Link;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
