// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function ProjectTile(Props) {
  var post = Props.post;
  React.useState(function () {
        return /* Image */1;
      });
  post.frontmatter.featuredimage;
  var possNullExternal = post.frontmatter.ext;
  var renderContentJsx = function (param) {
    return React.createElement("div", undefined, React.createElement("div", {
                    className: "font-bold text-xl mb-2"
                  }, post.frontmatter.title), React.createElement("p", {
                    className: "text-gray-700 text-base"
                  }, post.excerpt));
  };
  return React.createElement("div", {
              className: "max-w-sm rounded overflow-hidden shadow-lg h-64"
            }, React.createElement("div", {
                  className: "px-6 py-4"
                }, renderContentJsx(undefined)), React.createElement("div", undefined, (possNullExternal == null) ? null : React.createElement("a", {
                        href: possNullExternal,
                        rel: "noopener noreferrer",
                        target: "_blank"
                      }, "EXTERNAL LINK")), React.createElement("div", {
                  className: "px-6 py-4"
                }, Belt_Array.map(post.frontmatter.tech, (function (item) {
                        return React.createElement("span", {
                                    key: item,
                                    className: "inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2"
                                  }, item);
                      }))));
}

var Link;

var make = ProjectTile;

var $$default = ProjectTile;

exports.Link = Link;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
